services:
  pd:
    image: pingcap/pd:latest
    container_name: pd
    hostname: pd
    ports:
      - "2379:2379"
      - "2380:2380"
    command:
      - --name=pd
      - --data-dir=/pd/data
      - --client-urls=http://0.0.0.0:2379
      - --peer-urls=http://0.0.0.0:2380
      - --advertise-client-urls=http://pd:2379
      - --advertise-peer-urls=http://pd:2380
      - --initial-cluster=pd=http://pd:2380
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:2379/health"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - tidb_network

  tikv1:
    image: pingcap/tikv:latest
    container_name: tikv1
    hostname: tikv1
    ports:
      - "20160:20160"
      - "20180:20180"
    command:
      - --pd-endpoints=pd:2379
      - --addr=0.0.0.0:20160
      - --advertise-addr=tikv1:20160
      - --status-addr=0.0.0.0:20180
    depends_on:
      - pd
    networks:
      - tidb_network

  tikv2:
    image: pingcap/tikv:latest
    container_name: tikv2
    hostname: tikv2
    ports:
      - "20260:20260"
      - "20280:20280"
    command:
      - --pd-endpoints=pd:2379
      - --addr=0.0.0.0:20260
      - --advertise-addr=tikv2:20260
      - --status-addr=0.0.0.0:20280
    depends_on:
      - pd
    networks:
      - tidb_network

  tikv3:
    image: pingcap/tikv:latest
    container_name: tikv3
    hostname: tikv3
    ports:
      - "20360:20360"
      - "20380:20380"
    command:
      - --pd-endpoints=pd:2379
      - --addr=0.0.0.0:20360
      - --advertise-addr=tikv3:20360
      - --status-addr=0.0.0.0:20380
    depends_on:
      - pd
    networks:
      - tidb_network

  tidb:
    image: pingcap/tidb:latest
    container_name: tidb
    hostname: tidb
    ports:
      - "4000:4000"
      - "10080:10080"
    command:
      - --store=tikv
      - --path=pd:2379
      - --host=0.0.0.0
      - --status-host=0.0.0.0
    depends_on:
      - pd
      - tikv1
      - tikv2
      - tikv3
    networks:
      - tidb_network

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    hostname: prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    depends_on:
      - pd
      - tikv1
      - tikv2
      - tikv3
      - tidb
    networks:
      - tidb_network

  grafana:
    image: grafana/grafana
    container_name: grafana
    hostname: grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    networks:
      - tidb_network

networks:
  tidb_network:
    driver: bridge
