global:
  scrape_interval: 15s # Make sure this is longer than the scrape_timeout
  scrape_timeout: 10s # Set this to less than scrape_interval, or leave it unset to use the default

scrape_configs:
  - job_name: "pd"
    metrics_path: "/metrics"
    static_configs:
      - targets: ["172.18.0.2:2379"]
    relabel_configs:
      - source_labels: [__address__]
        target_label: job
        replacement: "pd" # Label for PD metrics

  - job_name: "tikv"
    metrics_path: "/metrics"
    static_configs:
      - targets: ["172.18.0.3:20180"]
    relabel_configs:
      - source_labels: [__address__]
        target_label: job
        replacement: "tikv" # Label for TiKV metrics

  - job_name: "tidb"
    metrics_path: "/metrics"
    static_configs:
      - targets: ["tidb:10080"]
    relabel_configs:
      - source_labels: [__address__]
        target_label: job
        replacement: "tidb" # Label for TiDB metrics

