global:
  scrape_interval: 15s
  scrape_timeout: 10s

scrape_configs:
  - job_name: "pd"
    metrics_path: "/metrics"
    static_configs:
      - targets: ["pd:2379"]
    relabel_configs:
      - source_labels: [__address__]
        target_label: job
        replacement: "pd"

  - job_name: "tikv"
    metrics_path: "/metrics"
    static_configs:
      - targets:
          - "tikv1:20180"
          - "tikv2:20280"
          - "tikv3:20380"
    relabel_configs:
      - source_labels: [__address__]
        target_label: job
        replacement: "tikv"

  - job_name: "tidb"
    metrics_path: "/metrics"
    static_configs:
      - targets: ["tidb:10080"]
    relabel_configs:
      - source_labels: [__address__]
        target_label: job
        replacement: "tidb"
