{
 "title": "TiKV Raft Consensus Metrics",
 "tags": [
  "raft",
  "tikv"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "instance",
    "query": "label_values(tikv_raftstore_proposal_total, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "Raft Proposal Rate",
   "type": "graph",
   "description": "Rate of Raft proposals being made",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(tikv_raftstore_proposal_total{instance=~\"$instance\"}[1m])) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Raft Leader Count",
   "type": "graph",
   "description": "Number of Raft leaders on each node",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(tikv_raftstore_region_count{instance=~\"$instance\", type=\"leader\"}) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Raft Message Receive/Send Rate",
   "type": "graph",
   "description": "Rate of Raft messages being sent and received",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(rate(tikv_server_raft_message_recv_total{instance=~\"$instance\"}[1m])) by (instance)",
     "legendFormat": "{{instance}} recv"
    },
    {
     "expr": "sum(rate(tikv_server_raft_message_sent_total{instance=~\"$instance\"}[1m])) by (instance)",
     "legendFormat": "{{instance}} send"
    }
   ]
  },
  {
   "title": "Raft Process Duration",
   "type": "graph",
   "description": "Time taken to process Raft messages",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(tikv_raftstore_process_duration_seconds_bucket{instance=~\"$instance\"}[1m])) by (le, instance))",
     "legendFormat": "{{instance}} p99"
    }
   ]
  },
  {
   "title": "Raft Apply Log Duration",
   "type": "graph",
   "description": "Time taken to apply Raft logs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(tikv_raftstore_apply_log_duration_seconds_bucket{instance=~\"$instance\"}[1m])) by (le, instance))",
     "legendFormat": "{{instance}} p99"
    }
   ]
  },
  {
   "title": "Raft Store Events",
   "type": "graph",
   "description": "Rate of different Raft store events",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "sum(rate(tikv_raftstore_event_duration_seconds_count{instance=~\"$instance\"}[1m])) by (instance, type)",
     "legendFormat": "{{instance}} - {{type}}"
    }
   ]
  }
 ]
}